#! /bin/bash
. ~/.config/mys.conf

file=$1
db=$2

copydb() {
    mysql -u ${MYS_NAME} --password=${MYS_PASS} ${db} < $file;
}

copydb > out.log 2> err.log

if [ $? -eq 0 ]; then
    printf -- "\e[32mSuccessfully copied ${file} into ${db}!\e[39m\n"
else
    printf -- "\e[31mOops! Something wasn't right, please check the mys_helper err.log\e[39m"
fi