#! /bin/bash
. ~/.config/mys.conf

db=$1

makedb() {
    mysql -u ${MYS_NAME} --password=${MYS_PASS} -e "create database ${db};"
}

makedb > out.log 2> err.log

if [ $? -eq 0 ]; then
    printf -- "\e[32mSuccessfully created ${db}!\e[39m\n"
else
    printf -- "\e[31mOops! Something wasn't right, please check the mys_helper err.log\e[39m"
fi